### ISSUE TITLE
What's about using travis-ci.org and Co. ?

### ISSUE THREAD

**Issue by jedie** [jvarho/pylibscrypt#13]
IMHO it's needful to use https://travis-ci.org and https://coveralls.io and maybe https://landscape.io

**Comment by jvarho** [comment]
Not really needful, but potentially useful if there were a lot of pull requests from other people. As is I just run 'make coverage' before pushing. I'll leave this issue open for now.

**Comment by jvarho** [comment]
Fixed in master
