### ISSUE TITLE
from foo import *

### ISSUE THREAD

**Issue by jedie** [jvarho/pylibscrypt#14]
First i found a start import in **example.py**... ok is't only the example...

Then i looked a little around and found many usage of star imports.

IMHO it's really bad practice.

**Comment by jvarho** [comment]
In the example I think it's ok, since that's the sort of thing you'd do in an interactive session to test things out. I'll review the other uses to see if any of them are problematic, but for imports within a package I also think it's fine and often better than a more verbose alternative.

**Comment by jvarho** [comment]
In fact, I reversed my opinion somewhat, no need to show practice contrary to PEP 8 in the examples. I've fixed that.

That left two uses:

1. Publishing the various implementations in \__init__.py. This is explicitly mentioned as a valid use case in PEP 8.
2. Importing common.py in most files. That's theoretically bad, so I fixed it, even though it resulted in ugly import statements.

**Comment by jedie** [comment]
:+1:
