### ISSUE TITLE
Error when libsodium misses a dependency

### ISSUE THREAD

**Issue by Insoleet** [jvarho/pylibscrypt#15]
Hi

If libsodium.dll misses a dependency (like visual C++ redistributables 2013), the lib throws an exception and doesnt use the python implementaion.

https://github.com/jvarho/pylibscrypt/blob/master/pylibscrypt/libsodium_load.py
```python
    sys_sodium = ctypes.util.find_library('sodium')
    if sys_sodium is None:
        sys_sodium = ctypes.util.find_library('libsodium')

    if sys_sodium:
        return ctypes.CDLL(sys_sodium)
```

If libsodium is present but misses a dependency, the find_library returns a correct path, but ctypes.CDLL throws an Exception.

**Comment by jvarho** [comment]
I'm having a hard time reproducing, since I don't have a Windows computer.

Is it sufficient to wrap the call in a try block like so:

        if sys_sodium:
            try:
                return ctypes.CDLL(sys_sodium)
            except:
                pass

Is the exception an OSError like the other cases, in which case I'd rather catch just it?

(Sorry for taking long to respond, summer.)
