### ISSUE TITLE
In the algorithm, 2**15 gives a valueerror

### ISSUE THREAD

**Issue by kootenpv** [jvarho/pylibscrypt#25]
But 2**14 still works. 

This is only in a recent version I think.

Note that 2**20 is still a possible value in the paper.

**Comment by jvarho** [comment]
Such numbers of `N` should work fine. Can you show your code? Does `make test` pass?

**Comment by kootenpv** [comment]
Cloned master, `make test` did indeed pass.

For me, this is a minimal example that doesn't work:

```python
from pylibscrypt import scrypt
# works
scrypt(b"a", b"a", 2**14)
# does not work
scrypt(b"a", b"a", 2**15)
```

Python version 3.6.1 on arch linux

Thanks for your quick reply :)

**Comment by kootenpv** [comment]
I see now it says:

    ValueError: Invalid paramemter combination for n, r, p, maxmem.

**Comment by jvarho** [comment]
Ah, it is because with Python 3.6 (+ openssl 1.1) you get scrypt from hashlib and I missed the fact that the default memory limit is only 32M, which is not enough for large parameter values.

I will write up a fix soon, but as a workaround you can use an earlier version than 1.6, modify the maxmem value in hashlibscrypt.py or import one of the other implementations directly.

**Comment by kootenpv** [comment]
I'm using `scrypt` as a password manager, so for now I'm using the very slow `pyscrypt`, I prefer to wait for an official pypi version.

Though you're right actually, it is quite simple to just change it, I'll do it. Thanks :)

**Comment by kootenpv** [comment]
I hacked the temp fix for myself indeed, changing maxmem. Please update the issue so others will know it has been resolved per some version :) 
(probably you planned to do that anyway)

**Comment by jvarho** [comment]
@kootenpv, thanks for helping me figure it out. I've pushed out an update which should fix this.

I would appreciate if you can test it out to make sure.

**Comment by kootenpv** [comment]
It indeed works :) Thanks a lot!
